name: Build CV with Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t awesome-cv -f .devcontainer/Dockerfile .

      - name: Run make inside Docker container
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace awesome-cv make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv-build-results
          path: |
            examples/*.pdf
